"""empty message

Revision ID: 76e0c583e527
Revises: d6202514e0b0
Create Date: 2019-07-20 10:27:06.086196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e0c583e527'
down_revision = 'd6202514e0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
