"""empty message

Revision ID: e98a498cca09
Revises: 76e0c583e527
Create Date: 2019-07-20 10:33:42.873220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98a498cca09'
down_revision = '76e0c583e527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.String(length=1024), nullable=False))
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###
